clone_depth: 200
version: '2020.1.{build}'

environment:
  matrix:
    - QTDIR: C:\Qt\5.10.1\msvc2015

configuration: Release

install:
  - choco install -y qbs --version 1.13.1
  - nuget install secure-file -ExcludeVersion
  - set PATH=%PATH%;%QTDIR%\bin

build_script:
  - qbs --version
  - qbs setup-toolchains --detect
  - qbs setup-qt %QTDIR%\bin\qmake.exe qt
  - qbs config defaultProfile qt
  - qbs build --all-products config:release
  - dir
  - 7z a -t7z ThunderEngine-%APPVEYOR_BUILD_VERSION%-windows-x86.7z release/install-root/

artifacts:
  - path: 'ThunderEngine*.7z'
    name: Binaries
